import { shell } from "electron";
import type { DownloadItem, DownloadPlatform, DownloadProgress, DownloadRequest, DownloadState } from "@moon/platform";
export interface DesktopDownloadBackend { start(request: DownloadRequest, onProgress: (progress: DownloadProgress) => void): Promise<DownloadItem>; pause(id: string): Promise<void>; resume(id: string): Promise<void>; cancel(id: string): Promise<void>; }
export class DesktopDownloads implements DownloadPlatform {
  readonly #items = new Map<string, DownloadItem>(); readonly #progress = new Map<string, DownloadProgress>();
  constructor(readonly backend: DesktopDownloadBackend) {}
  async start(request: DownloadRequest) { if (this.#items.has(request.id)) throw new Error(`Download already exists: ${request.id}`); const item = await this.backend.start(request, progress => this.#progress.set(request.id, progress)); this.#items.set(item.id, item); return item; }
  async pause(id: string) { await this.backend.pause(id); this.#setState(id, "paused"); } async resume(id: string) { await this.backend.resume(id); this.#setState(id, "in-progress"); } async cancel(id: string) { await this.backend.cancel(id); this.#setState(id, "cancelled"); }
  async retry(id: string) { const item = this.#require(id); return this.start({ ...item, id: `${id}-retry-${Date.now()}` }); } async get(id: string) { return this.#items.get(id) ?? null; } async list(options: { readonly state?: DownloadState; readonly limit?: number } = {}) { const items = [...this.#items.values()].filter(item => !options.state || item.state === options.state); return options.limit === undefined ? items : items.slice(0, options.limit); } async getProgress(id: string) { return this.#progress.get(id) ?? null; } async remove(id: string) { this.#items.delete(id); this.#progress.delete(id); } async openFile(id: string) { const item = this.#require(id); if (!item.savePath) throw new Error(`Download has no saved path: ${id}`); const error = await shell.openPath(item.savePath); if (error) throw new Error(error); } async showInFolder(id: string) { const item = this.#require(id); if (!item.savePath) throw new Error(`Download has no saved path: ${id}`); shell.showItemInFolder(item.savePath); } async clearHistory() { for (const [id,item] of this.#items) if (["completed","cancelled","failed"].includes(item.state)) await this.remove(id); } async shutdown() { for (const [id,item] of this.#items) if (["pending","in-progress","paused"].includes(item.state)) await this.cancel(id); }
  #require(id: string) { const item = this.#items.get(id); if (!item) throw new Error(`Download not found: ${id}`); return item; } #setState(id: string, state: DownloadState) { const item = this.#require(id); this.#items.set(id, { ...item, state }); }
}
