import { access, copyFile, mkdir, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs"; import { dirname, join, resolve } from "node:path"; import { app } from "electron";
import type { DirectoryEntry, FileMetadata, FileReadOptions, FilesystemPlatform, FileWriteOptions } from "@moon/platform";
export class DesktopFilesystem implements FilesystemPlatform {
  async exists(path: string) { try { await access(path); return true; } catch { return false; } }
  async stat(path: string): Promise<FileMetadata> { const value = await stat(path); let readonly = false; try { await access(path, constants.W_OK); } catch { readonly = true; } return { path, type: value.isFile() ? "file" : value.isDirectory() ? "directory" : value.isSymbolicLink() ? "symlink" : "unknown", size: value.size, createdAt: value.birthtimeMs, modifiedAt: value.mtimeMs, accessedAt: value.atimeMs, readonly }; }
  async readFile(path: string, options: FileReadOptions = {}) { const data = await readFile(path); if (options.maxBytes && data.byteLength > options.maxBytes) throw new Error(`File exceeds maximum size: ${path}`); return options.encoding === "base64" ? data.toString("base64") : options.encoding === "binary" ? new Uint8Array(data) : data.toString("utf8"); }
  async writeFile(path: string, data: string | Uint8Array, options: FileWriteOptions = {}) { if (!options.overwrite && await this.exists(path)) throw new Error(`File already exists: ${path}`); if (options.createDirectories) await mkdir(dirname(resolve(path)), { recursive: true }); const value = typeof data === "string" && options.encoding === "base64" ? Buffer.from(data, "base64") : data; await writeFile(path, value); }
  async deleteFile(path: string) { await rm(path); } async createDirectory(path: string, recursive = false) { await mkdir(path, { recursive }); } async deleteDirectory(path: string, recursive = false) { await rm(path, { recursive }); }
  async readDirectory(path: string): Promise<readonly DirectoryEntry[]> { const entries = await readdir(path, { withFileTypes: true }); return entries.map(entry => ({ name: entry.name, path: join(path, entry.name), type: entry.isFile() ? "file" : entry.isDirectory() ? "directory" : entry.isSymbolicLink() ? "symlink" : "unknown" })); }
  async copy(source: string, destination: string) { await copyFile(source, destination); } async move(source: string, destination: string) { await rename(source, destination); } async resolvePath(...segments: string[]) { return resolve(...segments); }
  async getApplicationDataPath() { return app.getPath("appData"); } async getUserDataPath() { return app.getPath("userData"); } async getDownloadsPath() { return app.getPath("downloads"); } async getCachePath() { return app.getPath("sessionData"); } async getTemporaryPath() { return app.getPath("temp"); }
}
